export const classData = [
    {
      id: "1",
      class: "Class 3",
      section: "SECTION A",
      noOfStudents: 36,
      subjects: ["MTH", "ENG", "BIO", "CHM", "PHY", "LAB"],
      male: 18,
      female: 18,
    },
    {
      id: "2",
      class: "Class 3",
      section: "SECTION A",
      noOfStudents: 36,
      subjects: ["MTH", "BIO", "CHM", "LAB"],
      male: 20,
      female: 16,
    },
    {
      id: "3",
      class: "Class 3",
      section: "SECTION A",
      noOfStudents: 36,
      subjects: ["MTH", "CHM", "LAB"],
      male: 14,
      female: 22,
    },
    {
      id: "4",
      class: "Class 3",
      section: "SECTION A",
      noOfStudents: 36,
      subjects: ["ENG", "PHY", "LAB"],
      male: 17,
      female: 19,
    },
  ];
  

  export const parentData = [
    {
      id: '1',
      fatherName: "David Werner",
      motherName: "Sasha Werner",
      username: "Werner001",
      date: "03-07-2024 | 01:16 PM",
      email: "thewerner@gmail.com",
      contact: "0817 585 5868",
      status: "Active",
      invited: "No",
      childName: "Alison Werner",
    },
    {
      id: '2',
      fatherName: "David Werner",
      motherName: "Sasha Werner",
      username: "Werner001",
      date: "03-07-2024 | 01:16 PM",
      email: "thewerner@gmail.com",
      contact: "0817 585 5868",
      status: "Alumni",
      invited: "Yes",
      childName: "Alison Werner",
    },
    {
      id: '3',
      fatherName: "John Doe",
      motherName: "Jane Doe",
      username: "theDoes",
      date: "03-07-2024 | 01:16 PM",
      email: "thedoes@gmail.com",
      contact: "0824 585 5868",
      status: "Alumni",
      invited: "No",
      childName: "Simpson Doe",
    },
    {
      id: '4',
      fatherName: "David Werner",
      motherName: "Sasha Werner",
      username: "Werner001",
      date: "03-07-2024 | 01:16 PM",
      email: "thewerner@gmail.com",
      contact: "0817 585 5868",
      status: "Alumni",
      invited: "Yes",
      childName: "Alison Werner",
    },
    // Add more data objects here...
  ];
  


  export const studentsData = [
    {
      id: "01",
      name: "Alison Werner",
      avatar: "https://via.placeholder.com/40",
      attendance: [
        "present",
        "absent",
        "present",
        "holiday",
        "present",
        "absent",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "holiday",
        "present",
        "absent",
        "null",
      ],
    },
    {
      id: "02",
      name: "John Doe",
      avatar: "https://via.placeholder.com/40",
      attendance: [
        "absent",
        "present",
        "absent",
        "present",
        "holiday",
        "present",
        "absent",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "holiday",
        "present",
        "absent",
      ],
    },
    // Add more students data up to 8
    {
      id: "03",
      name: "Jane Smith",
      avatar: "https://via.placeholder.com/40",
      attendance: [
        "present",
        "present",
        "absent",
        "holiday",
        "absent",
        "present",
        "absent",
        "present",
        "holiday",
        "absent",
        "present",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "present",
        "holiday",
        "absent",
        "present",
        "absent",
        "present",
        "holiday",
        "absent",
        "present",
      ],
    },
    {
      id: "04",
      name: "Emma Brown",
      avatar: "https://via.placeholder.com/40",
      attendance: [
        "absent",
        "absent",
        "present",
        "holiday",
        "present",
        "absent",
        "holiday",
        "present",
        "present",
        "absent",
        "holiday",
        "absent",
        "present",
        "holiday",
        "present",
        "absent",
        "present",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "present",
        "holiday",
        "present",
      ],
    },
    {
      id: "05",
      name: "Chris Evans",
      avatar: "https://via.placeholder.com/40",
      attendance: [
        "present",
        "holiday",
        "absent",
        "present",
        "absent",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "present",
        "holiday",
        "absent",
        "present",
        "absent",
        "present",
        "holiday",
        "absent",
        "present",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "present",
      ],
    },
    {
      id: "06",
      name: "Sophia Turner",
      avatar: "https://via.placeholder.com/40",
      attendance: [
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "present",
        "absent",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "present",
        "holiday",
        "absent",
        "present",
        "absent",
        "present",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "present",
        "holiday",
      ],
    },
    {
      id: "07",
      name: "Michael Scott",
      avatar: "https://via.placeholder.com/40",
      attendance: [
        "absent",
        "present",
        "holiday",
        "present",
        "absent",
        "present",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "holiday",
        "present",
        "absent",
        "present",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "present",
        "holiday",
        "absent",
        "present",
        "present",
      ],
    },
    {
      id: "08",
      name: "Pam Beesly",
      avatar: "https://via.placeholder.com/40",
      attendance: [
        "present",
        "present",
        "present",
        "holiday",
        "absent",
        "present",
        "absent",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "holiday",
        "present",
        "absent",
        "present",
        "holiday",
        "present",
        "absent",
        "holiday",
        "present",
        "absent",
        "present",
        "absent",
        "holiday",
      ],
    },
  ];