name: Node.js and React.js CI/CD for School padi with npm

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Adjust the Node.js version as needed

    steps:
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint
      - name: Run ESLint
        run: npm run lint

      # Build the project
      - name: Build frontend
        run: npm run build # Adjust the build command as needed
